steps:
  # Build and deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spot-the-artist'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'  # 30 minutes max (CLIP model download takes time)
